trigger:
  tags:
    include:
      - v*
  branches:
    include:
    - master


# test and upload my code as an artifact named WebSite
jobs:
- job: Build
  strategy:
    matrix:
      mac_36:
        imageName: 'macOS-10.14'
        python.version: '3.6'
      mac_37:
        imageName: 'macOS-10.14'
        python.version: '3.7'
      linux_py36:
        imageName: 'ubuntu-16.04'
        python.version: '3.6'
      linux_py37:
        imageName: 'ubuntu-16.04'
        python.version: '3.7'
  pool:
    vmImage: $(imageName)

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: python -m pip install --upgrade tiledb tiledb-cloud 'numpy==1.17.*' black pytest 
    # pip installs release candidates by default:
    #   https://github.com/pypa/pip/issues/4969
    displayName: 'Install dependencies'

  - script: black --check .
    displayName: 'Test Formatting'

  - bash: |
      set -xeo pipefail
      pytest
    # condition: eq(variables['Agent.OS'], 'Linux')
    env:
      TILEDB_REST_TOKEN: $(TILEDB_REST_TOKEN)
      AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
      AWS_SECRET_KEY_ID: $(AWS_SECRET_KEY_ID)
    displayName: "Run tests"
